### ISSUE TITLE
Revisar documentação e entregas anteriores

### ISSUE THREAD

**Issue by FelipeMallmann** [kappa-apps/kindly-app#27]

**Comment by brunovieira97** [comment]
A revisão foi concluída, sendo atualizados os documentos para refletir a realidade e estágio atual do projeto.

* Foram elaboradas novas User Stories (da 004 até a 012), cobrindo todas as funcionalidades até agora elencadas para o projeto. 
* O DAS (Documento de Arquitetura de Software) agora se encontra presente na Wiki, no formato Markdown, e não mais como um PDF externo. Durante o processo de reescrita, foi também atualizado para considerar o SGBD MySQL ao invés do MS SQL Server e adicionadas mais informações sobre a estrutura de diretórios.
* O Diagrama ER foi removido da pasta docs previamente existente no repositório, e disponibilizado na Wiki. Para isso, foi atualizado para conter novo campo na lista de necessidades (nome), na Instituição (descrição), e ajustado os relacionamentos Instituição-Ponto de Coleta, Endereço-Usuário e Endereço-Instituição.
* Issues criadas para representar funcionalidades dos MVPs (vinculadas aos milestones de MVP e não às sprints) foram editadas para referenciar as User Stories de suas funcionalidades.
