### ISSUE TITLE
Escrever guia de configuração do Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by FelipeMallmann** [kappa-apps/kindly-app#28]

**Comment by brunovieira97** [comment]
Escrevi uma listagem do que é necessário instalar para poder desenvolver para a API, e também os longos 3 passos que devem ser realizados pra configurar o ambiente kkk. @ohidalgojr só preciso de uma contribuição tua pra documentar o que vai ser necessário pro ambiente do front-end ;)

**Comment by brunovieira97** [comment]
O guia de configuração foi desenvolvido e disponibilizado na Wiki. Por ora, ele considera apenas o ambiente de desenvolvimento do back-end Java, e não o front-end JavaScript. Quando o desenvolvimento do front-end começar, @BiancaScheeren ou @ohidalgojr devem atualizar para incluir a seção do JS.
